version: '3.5'
services:
  development_http_proxy:
    image: httpd:latest
    networks:
      - logigator_intern
    volumes:
      - ./docker/development/httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - "80:80"
      - "443:443"
  development_backend:
    image: node:12
    networks:
      logigator_intern:
        aliases:
          - backend
    depends_on:
      - development_mysql
    volumes:
      - ./logigator-backend/:/home/node/app
    user: "node"
    working_dir: /home/node/app
    command: "npm start"
  development_mysql:
    image: mysql:latest
    networks:
      logigator_intern:
        aliases:
          - mysql
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=logigator
      - MYSQL_USER=logigator
      - MYSQL_PASSWORD=logigator

networks:
  logigator_intern:
    driver: bridge
