name: Release
on:
  create:
    tags:
      - '*'

jobs:
  relase:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: development

      - name: Setup Node
        uses: actions/setup-node@v1.1.0
        with:
          node-version: '12.x'

      - name: Build
        run: |
          npm i
          npm run build:electron:win64

      - name: Zip
        run: |
          zip -r release/Logigator-win32-x64.zip release/Logigator-win32-x64

      - name: Release
        uses: softprops/action-gh-release@v0.1.5
        with:
          tag_name: ${{ github.ref }}
          draft: false
          prereleas: false
          files: |
            release/Logigator-win32-x64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
